openapi:
  info:
    title: ${OPENAPI_INFO_TITLE:-Application API}
    description: ${OPENAPI_INFO_DESCRIPTION:-description}
    version: ${OPENAPI_INFO_VERSION:-v1.0}
    licence:
      name: ${OPENAPI_INFO_LICENCE_NAME:-Apache 2.0}
      url: ${OPENAPI_INFO_LICENCE_URL:-http://springdoc.org}
    contact:
      name: ${OPENAPI_INFO_CONTACT_NAME:-username}
      email: ${OPENAPI_INFO_CONTACT_EMAIL:-test@gmail.com}
  servers: '{"localhost:8080":"Dev server"}'


security:
  encryption:
    access-token-expiration-time-millis: '604800000'
    refresh-token-expiration-time-millis: '1209600000'
    access-token-key: 7yn6LXb4QIUUNPuxU5a18DVp4Dt5fbQA6PF6/OgvfPLWUsdvZCv95KlV+gsumL6WtjInxrabUlr2Mk2rom4vpQhBlcTh2RqRS70D2BOdW6rPL5HlZHdaJK4jzO46Dd4cz7rmHaN6+KGN/i3ZxUOwWI7GckSjyDZWa1CuAVV23lU=
    refresh-token-key: JOMLE3aX7UQaC1DUdQK8r8lj1d7tlh6ffDj+gc3nKB9L+pWFyeCYoo1SB7/uaNZqn5G5LdlrGw6xAJJ1l4gICzQvO/wWTCPXcru02m3P3966GuXwjW88AuBy33YvU8oGI5T58lHrfwaOaLq9rvcvNq8M97BLpWa4vR0szx7n24JGGqH9TBOj5iP0TJ4aEsO2
pdf:
  fonts:
    directory: ${DOCKER_FONTS_DIRECTORY:-src/main/resources/fonts/}

    classic: DejaVuSans.ttf
    bold: DejaVuSans-Bold.ttf
    size: '10'
    title_size: '20'
    subtitle_size: '16'
    encoding: cp1251
spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    driverClassName: org.postgresql.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    #    hikari:
    #      jdbcUrl: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/BusinessService}
    username: ${SPRING_DATASOURCE_USERNAME}
    url: ${SPRING_DATASOURCE_URL}
  liquibase:
    enabled: ${SPRING_ENABLE_LIQUIBASE:-true}
    drop-first: ${SPRING_ENABLE_LIQUIBASE_DROP_FIRST:-false}
    default-schema: public
  mvc:
    contentnegotiation:
      parameter-name: "format"
      default-type: application/json
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
            required: 'true'
          timeout: '5000'
          auth: 'true'
          connectiontimeout: '5000'
          writetimeout: '5000'
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME:-l99r000y.jenk1ns@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:-leeroooy99}
    port: '587'

server:
  error:
    include-binding-errors: always
    include-message: always
# Specify the path of the OpenAPI documentation
springdoc:
#  api-docs.path: /api-docs
  # Specify the path of the Swagger UI
  swagger-ui:
    path: /swagger-ui.html
  # Enable or disable Swagger UI
    enabled: true
logging:
  level:
    org:
      springframework:
        security: TRACE
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
